name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8

      - name: Format code with black
        run: |
          black app/main.py

      - name: Lint with flake8 (solo avisa)
        run: |
          flake8 app || echo "⚠️ Flake8 detectó advertencias (pero no se detiene el CI)"
